[project]
name = "async-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "fastapi>=0.116.1",
    "flask>=3.1.1",
    "pydantic>=2.11.7",
    "uvicorn>=0.35.0",
]
